# Generated by Django 5.2.5 on 2025-08-22 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0015_add_room_to_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to="cafe.room",
            ),
        ),
    ]
