# Generated by Django 5.2.8 on 2025-11-30 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0017_training_employee_employeedocument_hrdepartment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier for URLs",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trial", "Trial"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Restaurant-specific configuration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Restaurant",
                "verbose_name_plural": "Restaurants",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ["restaurant", "name"]},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["restaurant", "employee_id"]},
        ),
        migrations.AlterModelOptions(
            name="floor",
            options={"ordering": ["restaurant", "name"]},
        ),
        migrations.AlterModelOptions(
            name="hrdepartment",
            options={"ordering": ["restaurant", "name"]},
        ),
        migrations.AlterModelOptions(
            name="hrposition",
            options={"ordering": ["restaurant", "department__name", "name"]},
        ),
        migrations.AlterModelOptions(
            name="menu_item",
            options={"ordering": ["restaurant", "category", "name"]},
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ["restaurant", "department", "name"]},
        ),
        migrations.AlterModelOptions(
            name="staff",
            options={"ordering": ["restaurant", "employee_id"]},
        ),
        migrations.AddField(
            model_name="user",
            name="is_super_admin",
            field=models.BooleanField(
                default=False, help_text="Super admin can manage all restaurants"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(max_length=20, verbose_name="Employee ID"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="personnel_number",
            field=models.CharField(max_length=20, verbose_name="Personnel Number"),
        ),
        migrations.AlterField(
            model_name="floor",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="hrdepartment",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="hrposition",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="staff",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="staff",
            name="employee_id",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="table",
            name="table_number",
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name="bill",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="cafe.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="cafe.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="cafe.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="floor",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="floors",
                to="cafe.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="hrdepartment",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hr_departments",
                to="cafe.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="hrposition",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hr_positions",
                to="cafe.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="menu_item",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="cafe.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="cafe.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="cafe.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="cafe.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_members",
                to="cafe.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to="cafe.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                help_text="Restaurant this user manages (for restaurant admins)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admins",
                to="cafe.restaurant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("restaurant", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={
                ("restaurant", "employee_id"),
                ("restaurant", "personnel_number"),
            },
        ),
        migrations.AlterUniqueTogether(
            name="floor",
            unique_together={("restaurant", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="hrdepartment",
            unique_together={("restaurant", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="hrposition",
            unique_together={("restaurant", "name", "department")},
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("restaurant", "name", "department")},
        ),
        migrations.AlterUniqueTogether(
            name="staff",
            unique_together={("restaurant", "employee_id")},
        ),
        migrations.AlterUniqueTogether(
            name="table",
            unique_together={("restaurant", "table_number")},
        ),
    ]
