# Generated by Django 5.2.8 on 2025-11-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0018_restaurant_alter_department_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu_item",
            name="list_order",
            field=models.IntegerField(default=0),
        ),
    ]
