# Generated by Django 5.2.8 on 2025-11-30 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0019_add_list_order_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("codename", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("restaurant", "Restaurant Management"),
                            ("menu", "Menu Management"),
                            ("tables", "Table/Room Management"),
                            ("orders", "Order Management"),
                            ("employees", "Employee Management"),
                            ("payroll", "Payroll Management"),
                            ("attendance", "Attendance Management"),
                            ("leaves", "Leave Management"),
                            ("training", "Training Management"),
                            ("performance", "Performance Management"),
                            ("hr", "HR Management"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "ordering": ["category", "name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="cafe.employee",
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="approved_by_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_approved_leaves",
                to="cafe.employee",
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaves",
                to="cafe.employee",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("restaurant_admin", "Restaurant Admin"),
                    ("hr_manager", "HR Manager"),
                    ("staff", "Staff"),
                    ("customer", "Customer"),
                ],
                default="customer",
                help_text="User role in the system",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="cafe.staff",
            ),
        ),
        migrations.AlterField(
            model_name="hrdepartment",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_hr_departments",
                to="cafe.employee",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaves",
                to="cafe.staff",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("employee", "date")},
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("restaurant_admin", "Restaurant Admin"),
                            ("hr_manager", "HR Manager"),
                            ("staff", "Staff"),
                            ("customer", "Customer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="cafe.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Permission",
                "verbose_name_plural": "Role Permissions",
                "ordering": ["role", "permission"],
                "unique_together": {("role", "permission")},
            },
        ),
    ]
