# Generated by Django 5.2.8 on 2025-12-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0021_bill_currency_bill_invoice_number_bill_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu_item",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
