# Generated by Django 6.0.4 on 2026-04-16 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0022_alter_menu_item_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'permissions': [('can_mark_paid', 'Can mark bills and orders as paid'), ('can_create_bill', 'Can create or regenerate bills')]},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('can_place_waiter_order', 'Can place orders as waiter from tables'), ('can_view_kitchen_queue', 'Can view kitchen order queue for restaurant'), ('can_update_order_status_kitchen', 'Can advance order status as kitchen'), ('can_update_order_status_runner', 'Can advance order status as runner or waiter'), ('can_assign_runner', 'Can assign waiter to deliver prepared food')]},
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_runner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_assigned_to_deliver', to='cafe.staff'),
        ),
        migrations.AddField(
            model_name='order',
            name='kitchen_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='placed_by',
            field=models.CharField(choices=[('customer', 'Customer'), ('waiter', 'Waiter')], default='customer', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='placed_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_placed', to='cafe.staff'),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_consumed_at',
            field=models.DateTimeField(blank=True, help_text='When BOM stock was deducted for this order (idempotency).', null=True),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('unit', models.CharField(default='unit', help_text='e.g. kg, L, piece', max_length=30)),
                ('reorder_level', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cafe.restaurant')),
            ],
            options={
                'ordering': ['restaurant', 'name'],
                'permissions': [('can_manage_inventory', 'Manage ingredients, recipes, and stock adjustments'), ('can_view_inventory', 'View ingredients and stock levels')],
                'unique_together': {('restaurant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IngredientStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_level', to='cafe.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('partially_received', 'Partially received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='cafe.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_manage_purchase_order', 'Create and edit purchase orders'), ('can_receive_purchase_order', 'Receive purchase orders into stock')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=4, max_digits=14)),
                ('quantity_received', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='cafe.ingredient')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cafe.purchaseorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delta', models.DecimalField(decimal_places=4, help_text='Positive adds stock, negative removes', max_digits=14)),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase / receive'), ('adjustment', 'Manual adjustment'), ('consumption', 'Order consumption'), ('reversal', 'Reversal (e.g. cancelled order)'), ('waste', 'Waste / spoilage')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='cafe.ingredient')),
                ('order_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='cafe.order')),
                ('purchase_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='cafe.purchaseorderline')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='cafe.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='cafe.restaurant')),
            ],
            options={
                'ordering': ['restaurant', 'name'],
                'unique_together': {('restaurant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='cafe.supplier'),
        ),
        migrations.CreateModel(
            name='MenuItemRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Ingredient amount consumed per 1 unit of menu item sold', max_digits=14)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_usages', to='cafe.ingredient')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_lines', to='cafe.menu_item')),
            ],
            options={
                'unique_together': {('menu_item', 'ingredient')},
            },
        ),
    ]
