# Generated by Django 6.0.4 on 2026-04-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0029_saas_lifecycle_billing_audit'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bill',
            name='bill_rest_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_rest_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='staff',
            name='staff_rest_emp_idx',
        ),
        migrations.AlterField(
            model_name='restaurantsubscription',
            name='status',
            field=models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('pending_payment', 'Pending Payment'), ('failed', 'Failed'), ('past_due', 'Past Due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trialing', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='operational_access',
            field=models.CharField(choices=[('auto', 'From role title (waiter/chef keywords)'), ('waiter', 'Take orders & tables (waiter)'), ('kitchen_chef', 'Kitchen queue'), ('none', 'No waiter/kitchen portal access')], default='auto', help_text='Controls waiter/kitchen Django groups for the staff portal (manage-staff).', max_length=20),
        ),
    ]
