# Generated by Django 6.0.4 on 2026-04-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0030_remove_bill_bill_rest_time_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
